DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS projects;
CREATE TABLE IF NOT EXISTS users
(
    id    BIGSERIAL PRIMARY KEY,
    name  VARCHAR(200) NOT NULL UNIQUE ,
    email VARCHAR(254) NOT NULL UNIQUE ,
    password CHAR(32)  NOT NULL
);
CREATE TABLE IF NOT EXISTS projects
(
    id    BIGSERIAL PRIMARY KEY,
    name  VARCHAR(200) NOT NULL,
    email VARCHAR(254) NOT NULL,
    phone VARCHAR(20)  NOT NULL
);

CREATE TABLE IF NOT EXISTS projects_users
(
    project_id BIGSERIAL REFERENCES projects(id),
    owner_id BIGSERIAL REFERENCES users(id)
)